#ifndef __AI_H
#define __AI_H

#define AI_TEST
//#define ANT_EXPLORE

#define CLIPFAN_HIGH_HUMID   	90     // 90%

#define GROWLIGHT_HIGH_TEMP_F   130 
#define GROWLIGHT_HIGH_TEMP_C   55    	// 55 Cel

#define SENSOR_HIGH_TEMP_F   	100 
#define SENSOR_HIGH_TEMP_C   	38    	// 55 Cel

#define SENSOR_HIGH_HUMID_WARN	90

enum ai_on_events
{
	O_AI_OFF,
	O_AI_TIM_ON,
	O_AI_PID_ON,
	O_AI_VPD_ON
};
enum ai_events
{
	E_AI_OFF,
	E_AI_LIGHT,
	E_PID_HIGH,
	E_PID_LOW,
	E_AI_VPD_HIGH,
	E_AI_VPD_LOW,
	//E_AI_CO2_LOW,
	//E_AI_CO2_HIGH,
	//E_AI_SOIL_HUMID_LOW,
	//E_AI_SOIL_HUMID_HIGH,
	//E_AI_PH_LOW,
	//E_AI_PH_HIGH,
};
enum ai_states
{
	S_AI_START,
	S_AI_LIGHT,
	S_AI_TEMP,
	S_AI_HUMID,
	S_AI_VPD,
	//S_AI_CO2,
	//S_AI_PH,
	//S_AI_SOIL_HUMID,
	S_AI_END,
	NUMSENSORS,
};
enum ai_user_control_set_type
{
	USER_CONTROL_NONE,
	USER_CONTROL_TARGET,
	USER_CONTROL_START_END_TIME,
	USER_CONTROL_SUNRISE_SUNSET,
	USER_CONTROL_DEVICE_TYPE,
	USER_CONTROL_AI_PROGRAMMING,
	USER_CONTROL_SENSOR,
	USER_CONTROL_DYNAMIC_SUN,
	
	USER_CONTROL_MAX,
};

enum ai_user_control_change_type
{
	AI_CONTROL_NONE,
	AI_CONTROL_TEMP_F,
	AI_CONTROL_TEMP_C,
	AI_CONTROL_HUMID,
	AI_CONTROL_VPD,
};
enum ai_user_control_change_time
{
	AI_CONTROL_TIME_NONE,
	AI_CONTROL_START_END_TIME,
	AI_CONTROL_DURATIOM_TIME,
};
enum ai_control_sensor
{
	AI_CONTROL_SENSOR_NONE,
	AI_CONTROL_SENSOR_LOST,
	AI_CONTROL_SENSOR_SIDE,
};

enum{
	AI_USR_CONTROL_DYNAMIC_SUN_NONE,
	AI_USR_CONTROL_DYNAMIC_SUN_UAPDATE,
};

enum ml_log_type
{
	AI_NONE,
	AI_CONTROL,
	USER_CONTROL,
	AI_MODE_CONTROL,
	AI_ALERT,
};

enum ai_adjust_reason
{
	AI_ADJ_RESERVE = 0,
	AI_ADJ_RAISE_TEMP,
	AI_ADJ_LOWER_TEMP,
	AI_ADJ_RAISE_HUMID,
	AI_ADJ_LOWER_HUMID,
	AI_ADJ_RAISE_VPD,
	AI_ADJ_LOWER_VPD,
	AI_ADJ_MAINTAIN_CO2,
	AI_ADJ_IMPROVE_DEVICES_EFFICIENCY,
	AI_ADJ_RAISE_TEMP_HUMID,
	AI_ADJ_LOWER_TEMP_HUMID,
	AI_ADJ_RAISE_TEMP_LOWER_HUMID,
	AI_ADJ_LOWER_TEMP_RAISE_HUMID,
	AI_ADJ_REASONS_MAX,
};

enum ai_mode_control_change_type
{
	AI_PAUSED,
	AI_STARTED,
	AI_RESUMED,
	AI_DELETED,
	TEND_WORK_ACTIVATED,
	TEND_WORK_ENDED,
	EXTREME_TEMP_F_MAX100,
	EXTREME_TEMP_F_MAX130,
	EXTREME_TEMP_C_MAX38,
	EXTREME_TEMP_C_MAX55,
	EXTREME_HUMID_EXCEPT_FAN_MAX90,
	EXTREME_HUMID_FAN_MAX90,
	AI_GROW_STAGE_ENDED,
	AI_INSIGHT_UPDATED,
	EXTREME_TEMP_F_MAX130_GROWBOX,
	EXTREME_HUMID_MAX90_GROWBOX,
	NIGHT_MODE_ENABLED,		//log
	NIGHT_MODE_DISABLED,	//log
	CO2_ALERT,				//CO2<200ppm,message
	SOIL_ALERT,				//message
	WATER_DETECT_ALERT,		//message
	CO2_SAFETY_SHUTOFF,     //message
	HIGH_CO2_WITHOUT_REGULATOR, //message
	HIGH_CO2_WITH_REGULATOR,  //message
	AI_MODE_LOG_MAX,
};
#endif
